version: '1.0'

services:
  app:
    container_name: app_api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_HOST=db
      - DB_DATABASE:it_med
      - DB_USERNAME:root
      - DB_PASSWORD:
    ports:
      - 8000:8000
    volumes:
      - .:app
    depends_on:
      - db
    networks:
      - app
  
  db:
    container_name: app_db
    image: mysql:5.7.22
    environment:
      - MYSQL_DATABASE=it_med
      - MYSQL_USER=root
      - MYSQL_PASSWORD:
      - MYSQL_ROOT_PASSWORD:
    volumes:
      - .dbdata:var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - app

networks:
  app:
    driver: bridge